# Generated by Django 2.0.6 on 2018-11-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comic',
        ),
    ]
